### ISSUE TITLE
Problem with Spells/Abilities

### ISSUE THREAD

**Issue by juropo** [BurcinSayin/FG_PFRPG2_Upgrades#5]
I just installed this module, so I'm not sure if this a new bug introduced by the latest update or what.

I can't seem to get the spell rolls to work unless I have included both some kind of attack roll and a save roll in the Spell/Ability use window. I assume this is because the extra traits are only associated with the save. 

However, when I have both an attack and a save included, Fantasy Grounds will make two rolls when the button with the d20 is clicked. One roll is the Skill:VS:DC roll as expected, but the target will also roll a save, which is not what should happen. (I think FG maybe didn't use to roll the save before if an action had both an attack and a save.)

I can still make the VSDC roll by clicking the sword button now, but it's a little less convenient, because I have to click the magnifying glass to even get that button visible.

**Comment by BurcinSayin** [comment]
The cast action should have a safe type ( like fort, ref etc ) and you should set the DC of the save to fixed and smaller than zero like -1. 
There should be sample images in the readme file but I think the links are broken I will fix them as soon as possible

**Comment by BurcinSayin** [comment]
Sorry for that. Now I added a bit of text explanation and fixed the image links
